Backup Compatibility with Yours Wallet
BitcoinSchema/1sat-website pull request #39
Opened 2024-07-09 13:32 UTC by petarvx

This PR modifies the keys format in 1sat so they can be more compatible with Yours wallet.

2024-07-13 09:34 UTC, rohenaz commented
the vercel deploy failed and has some errors i think might actually be valid.

2024-07-15 08:22 UTC, petarvx commented
> the vercel deploy failed and has some errors i think might actually be valid.

You're right, sorry about that - fixed!

2024-07-16 08:08 UTC, rohenaz requested changes
I've tested this a bit and found a problem with derivation paths in the backup file after creating a new wallet.

- create a new wallet, export the keys
You will see derivation paths like
"payDerivationPath": "m/0/0/0/0/0"
but the key produced actually corresponds to "m/0" as it should

How I verified this:
- set aside the payment address for the new wallet to be verified
- go to bip39 tool: https://iancoleman.io/bip39/
- paste in the mnemonic from the backup file
- type in the base path "m"
- look at the produced addresses, you'll see m/0 (first address) corresponds to the payment address

should be an easy fix we just need to update the derivation paths to be m/0 for payment, m/X where X is the first 1s address. I've noted the lines that need to be changed.

same for ord key i got m/0/0/0/0/151 in the backup file instead of m/151

also we need to backport from alpha again there are some fixes in there

2024-07-16 08:08 UTC, rohenaz commented on src/utils/wallet.ts
> +		payPkDerivationPath = `m/0/0/0/0/${changeAddressPath.value}`;
this should be `m/${changeAddressPath.value}`

2024-07-16 08:08 UTC, rohenaz commented on src/utils/wallet.ts
> +		ordPkDerivationPath = `m/0/0/0/0/${ordAddressPath.value}`;
this should be `m/${ordAddressPath.value}`

2024-07-16 09:20 UTC, petarvx commented
> I've tested this a bit and found a problem with derivation paths in the backup file after creating a new wallet.
> 
> * create a new wallet, export the keys
>   You will see derivation paths like
>   "payDerivationPath": "m/0/0/0/0/0"
>   but the key produced actually corresponds to "m/0" as it should
> 
> How I verified this:
> 
> * set aside the payment address for the new wallet to be verified
> * go to bip39 tool: https://iancoleman.io/bip39/
> * paste in the mnemonic from the backup file
> * type in the base path "m"
> * look at the produced addresses, you'll see m/0 (first address) corresponds to the payment address
> 
> should be an easy fix we just need to update the derivation paths to be m/0 for payment, m/X where X is the first 1s address. I've noted the lines that need to be changed.
> 
> same for ord key i got m/0/0/0/0/151 in the backup file instead of m/151
> 
> also we need to backport from alpha again there are some fixes in there

Thank you for the explanation, that helped a lot! Updated 👍

2024-07-17 12:12 UTC, petarvx commented
Pushed an update to not assign payPk as identityPk as default when there is no identity key. Instead, we just won't have identity key if there isn't any.

2024-07-29 12:36 UTC, rohenaz approved these changes

2024-07-29 12:37 UTC, merged